#!/usr/bin/env bash
# installs with the init script

sudo apt-get install -y haproxy

# Ensure sudo is used for file operations
sudo sh -c '
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
touch /etc/haproxy/haproxy.cfg

# Redirect the entire content to avoid permission issues
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 5000
    timeout client 30000
    timeout server 30000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
frontend http-in
    timeout client 30000
    bind 0:80
    default_backend servers

backend servers
    timeout connect 3000
    timeout server 30000
    balance roundrobin
    server 462819-web-01 54.173.86.102 check
    server 462819-web-02 54.157.166.185 check
EOF
'

sudo service haproxy restart

